// =============================================================================
// Hand-written Drizzle table definitions for tables added by our own migrations
// (not by the legacy schema). These are NOT in drizzle/schema.ts because that
// file is regenerated by `pnpm db:introspect` from the legacy dump.
//
// Import from here via `../../db/schema` (which re-exports everything).
// =============================================================================
import { char, datetime, double, int, mysqlTable, varchar, index } from "drizzle-orm/mysql-core";
import { patientvisits, hcenterusers } from "../../drizzle/schema";

export const pvvitals = mysqlTable(
  "pvvitals",
  {
    pvVitalsId:       char("PVVitalsID",       { length: 36 }).notNull(),
    patientVisitId:   char("PatientVisitID",   { length: 36 }).notNull()
                        .references(() => patientvisits.patientVisitId, { onDelete: "cascade" }),
    recordedAt:       datetime("RecordedAt",   { mode: "string", fsp: 3 }).notNull(),
    recordedByUserId: char("RecordedByUserID", { length: 36 })
                        .references(() => hcenterusers.userId),

    heightCm:         double("HeightCm"),
    weightKg:         double("WeightKg"),
    bmi:              double("BMI"),
    sbp:              int("SBP"),
    dbp:              int("DBP"),
    pulseRate:        int("PulseRate"),
    temperatureC:     double("TemperatureC"),
    respiratoryRate:  int("RespiratoryRate"),
    spo2:             double("SpO2"),
    notes:            varchar("Notes", { length: 500 }),
  },
  (t) => [index("idx_pvv_visit").on(t.patientVisitId)],
);
