// =============================================================================
// Re-export the Drizzle schema generated by `pnpm db:introspect`.
//
// HARD RULE: do not hand-edit `apps/api/drizzle/schema.ts` — it is regenerated
// each time we introspect, and your edits will be lost. Aliasing and clean-name
// mapping happens in:
//   - DTOs:    packages/shared/src/types/*.ts       (already clean)
//   - Mappers: apps/api/src/modules/*/mappers.ts    (per feature, when built)
//
// The legacy DB has typo'd column names (CLAUDE.md hard rule #3) such as
// `Intesity`, `SourceOfRefferral`, `Breats`, `IsCacheBox`. In Drizzle TypeScript
// land these show up camelCased verbatim — `intesity`, `sourceOfRefferral`, etc.
// Reference them with that exact (typo'd) spelling in query code; never expose
// them past the mapper boundary.
// =============================================================================

export * from "../../drizzle/schema";
export * from "./custom-schema";
